# Generated by Django 3.1.5 on 2021-01-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_Forum', '0002_discussion_my_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='my_email',
        ),
    ]
