# Generated by Django 3.1.5 on 2021-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_Forum', '0003_remove_discussion_my_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='your_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
