# Generated by Django 3.1.3 on 2021-01-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QPapers',
        ),
    ]
