# Generated by Django 3.1.3 on 2021-01-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210102_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpapers',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
