# Generated by Django 3.1.3 on 2021-01-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_qpapers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpapers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qpapers',
            name='qpaper',
        ),
        migrations.RemoveField(
            model_name='qpapers',
            name='user_field',
        ),
        migrations.AddField(
            model_name='qpapers',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qpapers',
            name='Branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qpapers',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='qpapers',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
