# Generated by Django 3.1.3 on 2021-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210102_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(default='', max_length=50)),
                ('Subject', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=2021)),
                ('Semester', models.IntegerField(default=1)),
                ('college', models.CharField(default='', max_length=50)),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Texbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Author', models.CharField(default='', max_length=50)),
                ('Branch', models.CharField(default='', max_length=50)),
                ('Subject', models.CharField(default='', max_length=50)),
                ('PublicationYear', models.IntegerField(default=2021)),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='qpapers',
            old_name='Author',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='qpapers',
            name='Title',
        ),
        migrations.AddField(
            model_name='qpapers',
            name='Semester',
            field=models.IntegerField(default=1),
        ),
    ]
