# Generated by Django 3.1.3 on 2021-01-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210102_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpapers',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
    ]
