# Generated by Django 3.1.4 on 2021-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210103_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Branch',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='Subject',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='college',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapers',
            name='Branch',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapers',
            name='Subject',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qpapers',
            name='college',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='texbook',
            name='Author',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='texbook',
            name='Branch',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='texbook',
            name='Subject',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='texbook',
            name='Title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
