# Generated by Django 3.1.4 on 2021-01-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210103_1639'),
        ('webapp', '0010_auto_20210103_1142'),
    ]

    operations = [
    ]
